### ISSUE TITLE
Unable to compile TypeScript

### ISSUE THREAD

**Issue by john-cheesman** [Izhaki/Typescript-Jasmine-Istanbul-Boilerplate#4]
I've cloned the repo, installed the dependencies and tried both scripts. Both are failing to find the Jasmine type definition and even the module that's being tested can't be found

```
npm run test

> typescript-jasmine-istanbul-boilerplate@1.0.0 test /home/john/Sites/Typescript-Jasmine-Istanbul-Boilerplate
> ts-node node_modules/jasmine/bin/jasmine.js JASMINE_CONFIG_PATH=jasmine.json


/home/john/Sites/Typescript-Jasmine-Istanbul-Boilerplate/node_modules/ts-node/dist/index.js:160
                    throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset));
                    ^
TSError: ⨯ Unable to compile TypeScript
Cannot find type definition file for 'jasmine'. (2688)
src/Point.spec.ts (1,23): Cannot find module './Point'. (2307)
src/Point.spec.ts (3,1): Cannot find name 'describe'. (2304)
src/Point.spec.ts (5,5): Cannot find name 'describe'. (2304)
src/Point.spec.ts (7,9): Cannot find name 'it'. (2304)
src/Point.spec.ts (9,13): Cannot find name 'expect'. (2304)
src/Point.spec.ts (10,13): Cannot find name 'expect'. (2304)
src/Point.spec.ts (15,5): Cannot find name 'describe'. (2304)
src/Point.spec.ts (17,9): Cannot find name 'it'. (2304)
src/Point.spec.ts (21,13): Cannot find name 'expect'. (2304)

npm ERR! Linux 4.10.6-100.fc24.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! typescript-jasmine-istanbul-boilerplate@1.0.0 test: `ts-node node_modules/jasmine/bin/jasmine.js JASMINE_CONFIG_PATH=jasmine.json`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript-jasmine-istanbul-boilerplate@1.0.0 test script 'ts-node node_modules/jasmine/bin/jasmine.js JASMINE_CONFIG_PATH=jasmine.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the typescript-jasmine-istanbul-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ts-node node_modules/jasmine/bin/jasmine.js JASMINE_CONFIG_PATH=jasmine.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs typescript-jasmine-istanbul-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls typescript-jasmine-istanbul-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/john/Sites/Typescript-Jasmine-Istanbul-Boilerplate/npm-debug.log
```

I've tried adding a `tsconfig.json` and specifying `typeRoots` and `types` but it does't seem to help. Any ideas?

Thanks

**Comment by Izhaki** [comment]
Did `npm install` had any errors?

Can you see the folder `node_modules/@types/jasmine`?

**Comment by john-cheesman** [comment]
No, everything installed fine and I've got the jasmine types. I think it's a problem with ts-node on my system. I'll try and get it working on a different machine. 

Thanks for your help.

**Comment by Izhaki** [comment]
`ts-node` in this repo should run the local version, so doubt this has anything with your machine.

The first thing I'd try is to pin the dependencies in `package.json` (just remove the `^` before each dependency - my mistake not doing this), `rm -rf node_modules`, `npm install` and see if it works.

If this fails, I can see from your log you're using `Linux 4.10.6-100.fc24.x86_64`, but if you give me the exact distribution and version, I can test this very quickly using Docker.

**Comment by Izhaki** [comment]
On a separate note, technology-wise this repo is somewhat outdated. If you just want to get quickly off the ground, then I guess using it is OK.

But I owe to say that if you're after something more long-term than [nyc](https://github.com/istanbuljs/nyc) is the way to go - if I understand correctly, it's Istanbul's newer product for running coverage reports, and seems to be working very very well. Study [this issue](https://github.com/Izhaki/Typescript-Mocha-Istanbul-Boilerplate/issues/2) and the links within for more.

Also, since I've started using webpack I didn't look back (despite a rather steep learning curve), and that I'd vote for Mocha over Jasmine for serious projects. Jasmine is simple and great, but Mocha falls better into the 'compossible technology' paradigm, which I'm a strong believer of. It also has somewhat larger eco-system and a webpack driver.

Just my 2 cents (let me know if you want me to create a sample repository for this - I just need to copy-paste and clean an existing project).

**Comment by john-cheesman** [comment]
Pinning the dependencies fixed it, thanks. I've had the same problem with `ts-node` in other projects and it seems like getting the right versions of different packages is the key.

I've used Jasmine in the past and was looking for a simple test setup with Typescript but I'm definitely interested in looking at Mocha. If you could do a sample repo that would be great.

Thanks again for the help and advice.

**Comment by john-cheesman** [comment]
I had a go at a [basic setup](https://github.com/john-cheesman/ts-mocha-chai-nyc) and it works quite well.
